version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 758002376518.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Installing dependencies...
      - npm install

      - echo Building Angular app...
      - npm run build

      - echo Building Docker image...
      - docker build -t book-k8s-app:latest .

      - docker tag book-k8s-app:latest 758002376518.dkr.ecr.us-east-1.amazonaws.com/book-k8s-app:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push 758002376518.dkr.ecr.us-east-1.amazonaws.com/book-k8s-app:latest

      - echo Updating EKS deployment...
      - aws eks update-kubeconfig --name my-eks-cluster --region us-east-1

      - kubectl set image deployment/model-books my-book=758002376518.dkr.ecr.us-east-1.amazonaws.com/book-k8s-app:latest

      - kubectl rollout status deployment/model-books